# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps: 
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest ruff
        pip install python-dotenv rich google-generativeai
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Syntax check
      run: |
        ruff check
    - name: Test command
      run: |
        python llm.py --url https://blog.torproject.org/tor-is-still-safe --prompt "summary" |grep Tor
